### ISSUE TITLE
Unable to start receiver net.robotmedia.billing.BillingReceiver

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#19]
One of my user got the following error:

```
java.lang.RuntimeException: Unable to start receiver net.robotmedia.billing.BillingReceiver: java.lang.ClassCastException: android.preference.Preference
at android.app.ActivityThread.handleReceiver(ActivityThread.java:1805)
at android.app.ActivityThread.access$2400(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3683)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: android.preference.Preference
at spb.bridges.Preferences.onPurchaseExecuted(Preferences.java:89)
at net.robotmedia.billing.BillingController.notifyPurchaseStateChange(BillingController.java:242)
at net.robotmedia.billing.BillingController.onPurchaseStateChanged(BillingController.java:374)
at net.robotmedia.billing.BillingReceiver.purchaseStateChanged(BillingReceiver.java:57)
at net.robotmedia.billing.BillingReceiver.onReceive(BillingReceiver.java:44)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:1794)
... 10 more
```

What can be the reason?

**Comment by hpique** [comment]
According to that stack trace, the error is in `spb.bridges.Preferences`, line 89. That's not part of the library.

**Comment by and7ey** [comment]
hpique, here is the code of that Preferences line:

``` java
    @Override
    public void onPurchaseExecuted(String itemId) {     
        Log.i(TAG, "User bought ad-free version: "+itemId);
        CheckBoxPreference buyPref = (CheckBoxPreference) findPreference("pref_billing_buy");
        buyPref.setEnabled(false);
    }
```

does it run in some different context?

**Comment by hpique** [comment]
A ClassCastException seems to be the problem according to your stack trace.

**Comment by and7ey** [comment]
OK, looks like I understand why it happens. I've modified AbstractBillingActivity, now it extends PreferenceActivity, not just Activity. Seems the problem is somewhere here.

**Comment by hpique** [comment]
It should be noted that you don't need to use AbstracBillingActivity. You can use BillingController directly.

**Comment by and7ey** [comment]
I've used the following approach from the documentation

> Subclass AbstractBillingActivity in the activity in which you want to use in-app billing. 

I see now in DungeonsRedux example that BillingController can be used instead.
