### ISSUE TITLE
ANR crash when trying to purchase something without having market configured

### ISSUE THREAD

**Issue by ophidian** [robotmedia/AndroidBillingLibrary#32]
I just did a clean reset of my device. So I didn't setup my android market account yet.

I tried a purchase then, and i got this error:

E/AndroidRuntime( 1030): java.lang.RuntimeException: Unable to start service net.robotmedia.billing.BillingService@2b031a48 with Intent { act=com.ophidian.test.droid.RE
QUEST_PURCHASE cmp=com.ophidian.test.droid/net.robotmedia.billing.BillingService (has extras) }: java.lang.NullPointerException
E/AndroidRuntime( 1030):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2078)
E/AndroidRuntime( 1030):        at android.app.ActivityThread.access$2800(ActivityThread.java:124)
E/AndroidRuntime( 1030):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1010)
E/AndroidRuntime( 1030):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1030):        at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 1030):        at android.app.ActivityThread.main(ActivityThread.java:3715)
E/AndroidRuntime( 1030):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1030):        at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1030):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 1030):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 1030):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1030): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1030):        at android.os.Parcel.readException(Parcel.java:1328)
E/AndroidRuntime( 1030):        at android.os.Parcel.readException(Parcel.java:1276)
E/AndroidRuntime( 1030):        at com.android.vending.billing.IMarketBillingService$Stub$Proxy.sendBillingRequest(IMarketBillingService.java:100)
E/AndroidRuntime( 1030):        at net.robotmedia.billing.request.BillingRequest.run(BillingRequest.java:79)
E/AndroidRuntime( 1030):        at net.robotmedia.billing.BillingService.runRequest(BillingService.java:223)
E/AndroidRuntime( 1030):        at net.robotmedia.billing.BillingService.runRequestOrQueue(BillingService.java:237)
E/AndroidRuntime( 1030):        at net.robotmedia.billing.BillingService.requestPurchase(BillingService.java:200)
E/AndroidRuntime( 1030):        at net.robotmedia.billing.BillingService.handleCommand(BillingService.java:182)
E/AndroidRuntime( 1030):        at net.robotmedia.billing.BillingService.onStartCommand(BillingService.java:168)
E/AndroidRuntime( 1030):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2065)
E/AndroidRuntime( 1030):        ... 10 more
W/ActivityManager(  151):   Force finishing activity com.ophidian.test.droid/.billing.VaultActivity

**Comment by robotmedia** [comment]
Good catch. We didn't try this scenario.

Did checkBillingAvailable provide you a positive result?

**Comment by ophidian** [comment]
Sorry I didn't check that at the time. I'm currently crazy for a deadline on tuesday, but i'll give that a try afterwards.

Good job on the library btw, makes things a lot easier. Is there a way to -custom- inject subscriptions? eg by entering a code I'd activate a subscription on the device locally instead of via the market.

**Comment by uintaam** [comment]
I can confirm this same issue.

BillingController.checkBillingSupported() returns UNKNOWN in cases where the market isn't yet setup.  It also return's unknown if there is a pending Term's of Service agreement in the market on devices using 2.2, not sure about 2.1 or lower or 2.3.  3.x doesn't seem to have this issue, but I can only test it on one device the Motorola Xoom.

**Comment by robotmedia** [comment]
`checkBillingSupported` always returns UNKNOWN the first time it's executed. The actual status is sent to the observers of `BillingController`.

**Comment by uintaam** [comment]
In that case the observers are passing back supported.  All I could thing of doing was creating an optional call back function in the case that the app couldn't bind to the market, so the developer could throw up a warning or do something in the event that a bind didn't occur.

**Comment by robotmedia** [comment]
That's more or less what we planned to do. Not sure if we should at it to the observer interface, though. We'd like to keep it as simple as possible and this particular scenario is not very frequent.

**Comment by uintaam** [comment]
No it shouldn't be but I've already experienced the TOS (terms of service) version of this from 3 out of my 6 testers.  They don't use their devices frequently.  In the case of the TOS error, the application also doesn't always crash and I've observed users continuously hit buy buttons with no response from the Billing System other than a silent "Could not bind to MarketBillingService" in the logs.

It's also worth noting that even if the users go and accept the TOS, and return to the app there is still a binding issue for a few minutes... might be an Android issue more than a BillingLibrary issue, but if it can be worked around it would make users less confused.

**Comment by ludocrazy** [comment]
A)

@ophidian and @drewjw81 is this still present?

is it still reproduceable to wipe a device, NOT touch the market app (and thus not setup anything there), copy your own app onto the device and then reproduce above crash?

B)
does this crash report make sense? i mean, we are talking about google market in app purchases, that means someone needs to get your app AND needs to use google market. that means for me you will in 99,9% of all situations delive the (free) app to the user via google market. THEN he will use the billing features and thus the market will be configured properly.

if i understand the report above correctly (havent tested it myself), then the following happens:
-phone wiped, no market properly setup / TOS accetpted / etc.
-manually copied your (release build, sigend, non debuggable) APK onto the device
-app is started, library properly returns SUPPORTED and then simply does nothing when touching a "BUY THIS" button?
-because if it throws the NPE on the service, this means the intent is not started, which means that in a typicall code logic triggered by a button press nothing else is disturbed by the NPE. 

correct?

**Comment by shah0664** [comment]
I also have that issue, not produceable on my side but it is logged on developer console as it comes to some user for one of my game in android market.

**Comment by shah0664** [comment]
Can u help me on that..?
