### ISSUE TITLE
in app purchase android Compatibility. java InvocationTargetException issues

### ISSUE THREAD

**Issue by tikamchandrakar18** [robotmedia/AndroidBillingLibrary#45]
I am getting this issues when checkout activity is open and  back to the co

Compatibility.java file 

java.lang.reflect.InvocationTargetException

Please tell me how i can handle this ...

I have 3 activity 
1 Activity is the store e  name
2 activity is list of buy product lost 
3 Checkout  out screen ..

2 activity to 3 activity is working fine but when i came back from 2 to 1 and again goes to 3 activity (checkout activity ) after successfully bought it show following exception please tell me the solution for that..

 java.lang.reflect.InvocationTargetException
09-27 10:13:50.155: ERROR/Exception(20677):     at android.app.Activity.startIntentSender(Activity.java:2944)
09-27 10:13:50.155: ERROR/Exception(20677):     at java.lang.reflect.Method.invokeNative(Native Method)
09-27 10:13:50.155: ERROR/Exception(20677):     at java.lang.reflect.Method.invoke(Method.java:521)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.Compatibility.startIntentSender(Compatibility.java:77)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingController.startPurchaseIntent(BillingController.java:559)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.helper.AbstractBillingObserver.onPurchaseIntent(AbstractBillingObserver.java:58)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingController.onPurchaseIntent(BillingController.java:315)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingRequest$RequestPurchase.processOkResponse(BillingRequest.java:128)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingRequest.run(BillingRequest.java:246)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingService.runRequest(BillingService.java:223)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingService.runRequestOrQueue(BillingService.java:241)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingService.requestPurchase(BillingService.java:200)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingService.handleCommand(BillingService.java:182)
09-27 10:13:50.155: ERROR/Exception(20677):     at com.test.device.inapp.BillingService.onStartCommand(BillingService.java:168)
09-27 10:13:50.155: ERROR/Exception(20677):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3053)
09-27 10:13:50.155: ERROR/Exception(20677):     at android.app.ActivityThread.access$3600(ActivityThread.java:125)
09-27 10:13:50.155: ERROR/Exception(20677):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)

**Comment by funkyfourier** [comment]
I got this too, but fixed by implementing onDestroy in my Activity as in the Dungeons Redux example:

@Override
protected void onDestroy() {
    BillingController.unregisterObserver(mBillingObserver);
    super.onDestroy();
}

**Comment by ludocrazy** [comment]
@tikamchandrakar18 did you try @mrjohs steps? did it fix it for you? if yes, could you please close this issue? if not, did you fix it otherwise?

thx!

**Comment by Alocaly** [comment]
I have the same issue on my Nexus One, with Android 2.3.6.

One of the call to the startPurchaseIntent is throwing this exception.
And the activity has not been destroyed  (I don't destroyed it at this moment ), not even paused yet !

The rest of the exception says that :
11-03 18:33:56.235: E/Compatibility(3739): Caused by: android.content.IntentSender$SendIntentException
The [android developer page](http://developer.android.com/reference/android/content/IntentSender.SendIntentException.html) indicates that it means the pendingIntent is no longer able to execute the request.

At the moment of the exception, the very same call has been made just before.
Is it possible that there is a unnecessary call, and that the pendingIntent can't handle it ?

Last question : is there any real effect to this bug ? I feel like there is no real issue ( this version is on the market, and some customers have successfully bough some items ), but perhaps it causes some obscure bugs.

**Comment by Alocaly** [comment]
I investigated more on this issue, and found it is because I have two billing observers.
So the same pending intent is sent twice in a row, and the second time, it fails !

I'm not sure what the correct fix is...

**Comment by MrKalach** [comment]
Actual for me. On Xperia play same bug.

@Alocaly, maybe you have temporary fix?

**Comment by Alocaly** [comment]
@MrKalach 
I don't remind the whole story, but as I said, it was caused by using two billing observers.
So I rewrite my code to only have on observer, and every thing was fine again...

Hope it helps !
