### ISSUE TITLE
NullPointerException Parcel

### ISSUE THREAD

**Issue by BraisGabin** [robotmedia/AndroidBillingLibrary#60]
I'm getting these crash logs from Google Play. I think this crash is related to this: http://stackoverflow.com/questions/8118609/how-to-resolve-this-error-in-in-app-billing

``` java
java.lang.NullPointerException
at android.os.Parcel.readException(Parcel.java:1328)
at android.os.Parcel.readException(Parcel.java:1276)
at com.android.vending.billing.IMarketBillingService$Stub$Proxy.sendBillingRequest(IMarketBillingService.java:100)
at net.robotmedia.billing.BillingRequest.run(BillingRequest.java:238)
at net.robotmedia.billing.BillingService.runRequest(BillingService.java:230)
at net.robotmedia.billing.BillingService.runPendingRequests(BillingService.java:213)
at net.robotmedia.billing.BillingService.onServiceConnected(BillingService.java:147)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1064)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1081)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3691)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
at dalvik.system.NativeStart.main(Native Method)
```

``` java
java.lang.NullPointerException
at android.os.Parcel.readException(Parcel.java:1328)
at android.os.Parcel.readException(Parcel.java:1276)
at com.android.vending.billing.IMarketBillingService$Stub$Proxy.sendBillingRequest(IMarketBillingService.java:100)
at net.robotmedia.billing.BillingRequest.run(BillingRequest.java:238)
at net.robotmedia.billing.BillingService.runRequest(BillingService.java:230)
at net.robotmedia.billing.BillingService.runPendingRequests(BillingService.java:213)
at net.robotmedia.billing.BillingService.runRequestOrQueue(BillingService.java:243)
at net.robotmedia.billing.BillingService.requestPurchase(BillingService.java:197)
at net.robotmedia.billing.BillingService.handleCommand(BillingService.java:179)
at net.robotmedia.billing.BillingService.onStartCommand(BillingService.java:165)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2043)
... 10 more
```

**Comment by uintaam** [comment]
I'm testing an update here https://github.com/drewjw81/AndroidBillingLibrary/commits/master that displays an alert when we can't bind to the Billing Library.  If it's not solving your issue let me know and I can make adjustments.  Also note the update isn't yet heavily tested.

**Comment by hpique** [comment]
This appears to be a known IAB bug reported here: http://code.google.com/p/marketbilling/issues/detail?id=25

I've added a catch when this occurs in this commit: https://github.com/robotmedia/AndroidBillingLibrary/commit/b11124363048a545ed0321afb7ded7a8104d55fc
