### ISSUE TITLE
SendIntentException when exiting billing client frame

### ISSUE THREAD

**Issue by pszNicx** [robotmedia/AndroidBillingLibrary#63]
I'm trying to use the AbstractBillingActivity in a single Activity app. It's just one activity because it's an NDK game. I implemented everything exactly as in the documentation and it seems to work on my ASUS Transformer Android tablet running ICS. The problem is it crashes with the following exception on other devices when I have people test it. I don't have access to the other devices so all I have to work from is this log. According to what they tell me, as soon as they either accept the purchase or cancel out, whenever the billing window exits, it crashes with this log:

05-02 20:47:22.750: E/Compatibility(958): startIntentSender
05-02 20:47:22.750: E/Compatibility(958): java.lang.reflect.InvocationTargetException
05-02 20:47:22.750: E/Compatibility(958):   at java.lang.reflect.Method.invokeNative(Native Method)
05-02 20:47:22.750: E/Compatibility(958):   at java.lang.reflect.Method.invoke(Method.java:507)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.utils.Compatibility.startIntentSender(Compatibility.java:65)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingController.startPurchaseIntent(BillingController.java:565)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.helper.AbstractBillingObserver.onPurchaseIntent(AbstractBillingObserver.java:58)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingController.onPurchaseIntent(BillingController.java:325)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingRequest$RequestPurchase.processOkResponse(BillingRequest.java:128)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingRequest.run(BillingRequest.java:247)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingService.runRequest(BillingService.java:230)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingService.runPendingRequests(BillingService.java:213)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingService.runRequestOrQueue(BillingService.java:243)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingService.requestPurchase(BillingService.java:197)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingService.handleCommand(BillingService.java:179)
05-02 20:47:22.750: E/Compatibility(958):   at net.robotmedia.billing.BillingService.onStartCommand(BillingService.java:165)
05-02 20:47:22.750: E/Compatibility(958):   at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2039)
05-02 20:47:22.750: E/Compatibility(958):   at android.app.ActivityThread.access$2800(ActivityThread.java:117)
05-02 20:47:22.750: E/Compatibility(958):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:994)
05-02 20:47:22.750: E/Compatibility(958):   at android.os.Handler.dispatchMessage(Handler.java:99)
05-02 20:47:22.750: E/Compatibility(958):   at android.os.Looper.loop(Looper.java:130)
05-02 20:47:22.750: E/Compatibility(958):   at android.app.ActivityThread.main(ActivityThread.java:3683)
05-02 20:47:22.750: E/Compatibility(958):   at java.lang.reflect.Method.invokeNative(Native Method)
05-02 20:47:22.750: E/Compatibility(958):   at java.lang.reflect.Method.invoke(Method.java:507)
05-02 20:47:22.750: E/Compatibility(958):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
05-02 20:47:22.750: E/Compatibility(958):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
05-02 20:47:22.750: E/Compatibility(958):   at dalvik.system.NativeStart.main(Native Method)
05-02 20:47:22.750: E/Compatibility(958): Caused by: android.content.IntentSender$SendIntentException
05-02 20:47:22.750: E/Compatibility(958):   at android.app.Activity.startIntentSenderForResultInner(Activity.java:2896)
05-02 20:47:22.750: E/Compatibility(958):   at android.app.Activity.startIntentSenderForResult(Activity.java:2875)
05-02 20:47:22.750: E/Compatibility(958):   at android.app.Activity.startIntentSender(Activity.java:2954)
05-02 20:47:22.750: E/Compatibility(958):   ... 25 more

Can anyone help point me in the direction of a solution?

**Comment by davidcesarino** [comment]
I'm having the same issue.

**Comment by schlingel** [comment]
Me too - did anybode of you get a work around?

**Comment by MrFloppyCoding** [comment]
same here. what's going on?

**Comment by srikanthnama** [comment]
HI @pszNicx  I am also facing the same issue.. Have you got the solution for this? If so please help me in this..
